import Head from 'next/head';
import Image from 'next/image';
import Chat from '../components/Chat';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="whatsapp-logo-png-2261.png" />
      </Head>

      <div style={{ display: 'flex' }}>
        <Sidebar />
      </div>
    </div>
  );
}
